name: "Deploy Storybook"

on:
  push:
    branches:
      - "master"

jobs:
  publish-storybook:
    permissions:
      id-token: "write"
      pages: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: actions/checkout@v7

      - id: "setup-node"
        name: "Set up Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run: npm install

      - id: "build"
        name: "Build Storybook"
        run: |
          npm run build
          npm run build-demo

      - id: "upload-storybook"
        name: "Upload Pages artifact"
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5
        with:
          path: "storybook/"

      - id: "deployment"
        name: "Deploy Storybook to GitHub Pages"
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5
