name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
